### ISSUE TITLE
IMC atualização

### ISSUE THREAD

**Issue by mariaraujo815** [pylearners/IMC#11]
Inclua no exercício de IMC uma atualização (com commit e documentação atualizada(seguir o fluxo padrão de atualização de códigos, documente a necessidade de uma nova funcionalidade no programa, cadastre ao projeto um novo milestone com issues associados)):
Requisito:
Receber o IMC utilizando a função input

**Comment by nataliasouza1306** [comment]
Fiz da seguinte maneira: 

peso = float (input("Digite o seu peso: "))
altura = float (input("Digite sua altura: "))

imc = (peso/(altura**2))

print("O peso informado foi: %s, e a altura informada foi: %s" %(peso, altura))
print("Portanto, o seu IMC é: ", imc)

**Comment by livianascimento01** [comment]
está na atividade 1 e 2

**Comment by FabioISD** [comment]
Código final já foi postado, faltando apenas o WIKI
