### ISSUE TITLE
IMC exercicio 3

### ISSUE THREAD

**Issue by mariaraujo815** [pylearners/IMC#12]
Inclua no exercício de IMC uma atualização (com commit e documentação atualizada(seguir o fluxo padrão de atualização de códigos, documente a necessidade de uma nova funcionalidade no programa, cadastre ao projeto um novo milestone com issues associados)):
Requisito:
Apresentar na tela apenas o IMC e a faixa na qual o operador se encaixa

**Comment by nataliasouza1306** [comment]
Ok! Código adicionado!
